### ISSUE TITLE
ouctl not respecting the dashboard namespace?

### ISSUE THREAD

**Issue by johanneskastl** [TremoloSecurity/openunison-control#21]
I have this in my `values.yaml`:

```
dashboard:
  namespace: openunison
```

However, during deployment with `ouctl install-auth-portal OpenUnison/values.yaml` I get a different namespace for the dashboard, and this other namespace is being created:

```
Checking for the Dashboard namespace kubernetes-dashboard
Dashboard namespace kubernetes-dashboard does not exist, creating
Dashboard namespace kubernetes-dashboard created
Checking for the OpenUnison namespace openunison
OpenUnison namespace openunison already exists
```

Looks like ouctl does not respect the settings in my `values.yaml` file. Or did I misunderstand the purpose of the dashboard.namespace key?

**Comment by mlbiam** [comment]
can you share your values.yaml?  Looking at the code i see it looking for dashboard configuration

**Comment by johanneskastl** [comment]
I tried several variants, I also tried disabling the dashboard.

```
---                                                                                                                                                                                          
network:                                                                                                                                                                                     
  openunison_host: "openunison.deskmini.example.org"                                                                                                                                         
  dashboard_host: "dashboard.deskmini.example.org"                                                                                                                                           
  api_server_host: "api-server.deskmini.example.org"                                                                                                                                         
  k8s_url: https://XXX:6443                                                                                                                                                                  
  force_redirect_to_tls: true                                                                                                                                                                
  createIngressCertificate: false                                                                                                                                                            
  ingress_type: nginx                                                                                                                                                                        
  ingress_certificate: openunison.deskmini.example.org-tls                                                                                                                                   
                                                                                                                                                                                             
k8s_cluster_name: deskmini                                                                                                                                                                   
                                                                                                                                                                                             
dashboard:                                                                                                                                                                                   
  namespace: openunison                                                                                                                                                                      
  cert_name: dashboard.deskmini.example.org-tls                                                                                                                                              
  label: "k8s-app=kubernetes-dashboard"                                                                                                                                                      
  service_name: kubernetes-dashboard                                                                                                                                                         
  require_session: true                                                                                                                                                                      
                                                                                                                                                                                             
active_directory:                                                                                                                                                                            
  base: ou=users,dc=example,dc=org                                                                                                                                                           
  host: ldap.example.org                                                                                                                                                                     
  port: 636                                                                                                                                                                                  
  bind_dn: cn=admin,dc=example,dc=org                                                                                                                                                        
  con_type: ldaps                                                                                                                                                                            
  srv_dns: "false"
```
