### ISSUE TITLE
Change the secret name for the ingress TLS certificate?

### ISSUE THREAD

**Issue by johanneskastl** [TremoloSecurity/openunison-control#23]
Can the secret name for the ingress TLS certificate be changed?

I can enable/disable generation of the certificate according to the default values, but I cannot set the name?

```
network:                                                                                                                                                                                     
  [...]
  force_redirect_to_tls: false                                                                                                                                                               
  createIngressCertificate: true                                                                                                                                                             
  ingress_type: nginx                                                                                                                                                                        
  ingress_annotations: {}
```

I found a mention of `ingress_certificate`, but that does nothing in my tests?
